# SPDX-FileCopyrightText: 2021-2023 Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

name: Go fuzzing
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.18, 1.19]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Run Fuzzing Tests
      run: |
        go version && go test -v -race -fuzz=. --fuzztime=10s . && go test -v -race -fuzz=. --fuzztime=10s ./rfc3164 && go test -v -race -fuzz=. --fuzztime=10s ./rfc5424
