# SPDX-FileCopyrightText: 2021-2023 Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

name: SonarQube
on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    branches:
      - main # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'
          
      - name: Run unit Tests
        run: |
          go test -v -race --coverprofile=./cov.out ./...

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
